name: cities-thermal
channels:
  - conda-forge/label/qgis_ltr
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - gdal=3.10.3
  - numpy=1.26.4
  - matplotlib=3.10.1
  - qgis=3.40.6
  - matplotlib=3.10.1
  - scipy=1.15.2
  - conda-build=25.4.2
  - dask[complete]=2025.3.0
  - rasterio=1.4.3
  - rioxarray=0.19.0
  - cdsapi=0.7.5
  - pytest=8.3.5
  - pytest_check=2.5.1
  - utm=0.7.0
  - shapely=2.1.0
  - pip=25.0.1
  - pip:
    - git+https://github.com/wri/cities-cif@CDB-306-Explore-moving-OpenUrban-class-from-C-TCM-to-CIF
  #   - git+https://github.com/wri/cities-cif@v0.1.2
