name: cities-thermal
channels:
  - conda-forge/label/qgis_ltr
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - gdal=3.10.3
  - pandas=2.2.3
  - matplotlib=3.10.3
  - qgis=3.40.6
  - matplotlib=3.10.3
  - scipy=1.15.2
  - numpy=2.2.5
  - jaydebeapi=1.2.3
  - numba=0.61.2
  - conda-build=25.4.2
  - dask[complete]<=2025.2.0
  - rasterio=1.4.3
  - rioxarray=0.19.0
  - cdsapi=0.7.5
  - pytest=8.3.5
  - pytest_check=2.5.1
  - utm=0.7.0
  - shapely=2.1.0
  - pip=25.0.1
  - pip:
    - git+https://github.com/wri/cities-cif@CDB-214-Explore-running-ctcm-on-linux
  #   - git+https://github.com/wri/cities-cif@v0.1.2
