name: cities-thermal
channels:
  - conda-forge/label/qgis_ltr
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - gdal=3.9.2
  - numpy=1.26.4
  - matplotlib=3.10.1
  - qgis=3.34.11
  - matplotlib==3.10.1
  - scipy=1.15.2
  - conda-build=25.1.2
  - dask[complete]=2025.2.0
  - rasterio=1.4.1
  - rioxarray=0.18.2
  - cdsapi=0.7.5
  - pytest=8.3.5
  - pytest_check=2.5.0
  - utm=0.7.0
  - shapely=2.0.7
  - pip=25.0.1
  - pip:
    - git+https://github.com/wri/cities-cif@main
  #   - git+https://github.com/wri/cities-cif@v0.1.2
