# Configurable attribute values for method processing
- MethodAttributes:
  wall_height_aspect:
    lower_limit_for_wall_height: 3
  skyview_factor:
    transmissivity_of_light_through_vegetation: 3
    trunk_zone_height: 25
  solweig:
    leaf_start: 97
    leaf_end: 300
    conifer_trees: False
    albedo_walls: 0.2
    albedo_ground: 0.15
    emis_walls: 0.9
    emis_ground: 0.95
    output_tmrt: True
    output_sh: True
# Names of meteorological files used by SOLWEIG method in "UMEP for Processing" plugin.
# Specify custom files or "download_era5" to trigger automatic download of ERA5 data to file named met_era5_hottest_days.txt
- MetFiles:
  - filename: met_20jan2022.txt
  - filename: met_22jan2022.txt
# Custom source-files that were independently created and will replace standard files pulled from CIF system.
# All four file mappings must be specified here. Specify None for filename where custom file is not available for processing.
# Recommended filenames: dem.tif, dsm_ground_build.tif, tree_canopy.tif, lulc.tif
# Auto-generated filenames from CIF: cif_dem.tif, cif_dsm_ground_build.tif, cif_tree_canopy.tif, cif_lulc.tif
- CustomTiffFilenames:
  dem_tif_filename: dem.tif
  dsm_tif_filename: dsm_ground_build.tif
  tree_canopy_tif_filename: tree_canopy.tif
  lulc_tif_filename: lulc.tif
# Processing Area of Interest used for tile construction and ERA5-data download. If any custom files
# are specified above, then the system will not construct a new tile grid and will instead use the existing one.
# If you don't want to subdivide the AOI, specify None for tile_side_meters and tile_buffer_meters.
- ProcessingAOI:
  utc_offset: 2
  min_lon: 18.41294
  min_lat: -33.92100
  max_lon: 18.41401
  max_lat: -33.91999
  tile_side_meters: None
  tile_buffer_meters: None