# Configurable attribute values for method processing
- MethodAttributes:
  wall_height_aspect:
    lower_limit_for_wall_height: 3
  skyview_factor:
    transmissivity_of_light_through_vegetation: 3
    trunk_zone_height: 25
  solweig:
    leaf_start: 97
    leaf_end: 300
    conifer_trees: False
    albedo_walls: 0.2
    albedo_ground: 0.15
    emis_walls: 0.9
    emis_ground: 0.95
    output_tmrt: True
    output_sh: True
# Names of meteorological files used for SOLWEIG processing
# Specify met_era5_hottest_days.txt if you want the system to automatically download era5 data
- MetFiles:
  - filename: met_20jan2022.txt
  - filename: met_era5_hottest_days.txt
# Custom source-files that were independently created and will replace standard files pulled from CIF system.
# All four file mappings must be specified here. Specify None for filename where custom file is not available for processing.
# Recommended filenames: dem.tif, dsm_ground_build.tif, tree_canopy.tif, lulc.tif
# Auto-generated filenames from CIF: cif_dem.tif, cif_dsm_ground_build.tif, cif_tree_canopy.tif, cif_lulc.tif
- CustomTiffFilenames:
  dem_tif_filename: None
  dsm_tif_filename: None
  tree_canopy_tif_filename: None
  lulc_tif_filename: None
# New processing Area of Interest. If any custom files are specified above (i.e. not None), then the system will not construct
# a new tile grid and will instead use the existing one. In that case, coordinate values below can be None.
# If you don't want to subdivide the AOI, specify None for tile_side_meters and tile_buffer_meters.
- ProcessingAOI:
  utc_offset: 2
  min_lon: 4.9011
  min_lat: 52.3719
  max_lon: 4.9183
  max_lat: 52.3852
  tile_side_meters: 500
  tile_buffer_meters: 20
