# Configurable attribute values for method processing
- MethodAttributes:
  wall_height_aspect:
    lower_limit_for_wall_height: 3
  skyview_factor:
    transmissivity_of_light_through_vegetation: 3
    trunk_zone_height: 25
  solweig:
    leaf_start: 97
    leaf_end: 300
    conifer_trees: False
    albedo_walls: 0.2
    albedo_ground: 0.15
    emis_walls: 0.9
    emis_ground: 0.95
    output_tmrt: True
    output_sh: True
# Names of meteorological files used for SOLWEIG processing
- MetFiles:
  - filename: <met_filename_1>.txt
    utc_offset: <n>
  - filename: <met_filename_2>.txt
    utc_offset: <n>
# Name of source files used for processing. All tiles must use the same file names.
# Note that the names below are the recommended names, but you can specify different ones.
- Tifffilenames:
  dem_tif_filename: dem.tif
  dsm_ground_build_tif_filename: dsm_ground_build.tif
  veg_canopy_tif_filename: tree_canopy.tif
  landcover_tif_filename: landcover.tif
