# Configurable attribute values for method processing
- MethodAttributes:
  wall_height_aspect:
    lower_limit_for_wall_height: 3
  skyview_factor:
    transmissivity_of_light_through_vegetation: 3
    trunk_zone_height: 25
  solweig:
    leaf_start: 97
    leaf_end: 300
    conifer_trees: False
    albedo_walls: 0.2
    albedo_ground: 0.15
    emis_walls: 0.9
    emis_ground: 0.95
    output_tmrt: True
    output_sh: True
# Names of meteorological files used for SOLWEIG processing
- MetFiles:
  - filename: <met_filename_1>.txt
    utc_offset: <n>
  - filename: <met_filename_2>.txt
    utc_offset: <n>
# Custom source-files that were independently created and will replace standard files pulled from CIF system.
# All four file mappings must be specified here. Specify None for file name where custom file is not available for processing.
# Standard filenames: dem.tif, dsm_ground_build.tif, tree_canopy.tif, lulc.tif
- CustomTiffFilenames:
  dem_tif_filename: dem.tif
  dsm_ground_build_tif_filename: dsm_ground_build.tif
  tree_canopy_tif_filename: tree_canopy.tif
  lulc_tif_filename: lulc.tif
# Specify whether standard source-files will be retrieved from the CIF system. All four file mappings must be specified here.
# Specify "True" for CIF retrieval and "False" for no CIF retrieval in quotes.
# Retrieved filenames: cif_dem.tif, cif_dsm_ground_build.tif, cif_tree_canopy.tif, cif_lulc.tif
- RetrieveTiffFileFromCIF:
  dem_tif_filename: "False"
  dsm_ground_build_tif_filename: "False"
  tree_canopy_tif_filename: "False"
  lulc_tif_filename: "False"
