# Configurable attribute values for method processing
- MethodAttributes:
  wall_height_aspect:
    lower_limit_for_wall_height: 3
  skyview_factor:
    transmissivity_of_light_through_vegetation: 3
    trunk_zone_height: 25
  solweig:
    leaf_start: 97
    leaf_end: 300
    conifer_trees: False
    albedo_walls: 0.2
    albedo_ground: 0.15
    emis_walls: 0.9
    emis_ground: 0.95
    output_tmrt: True
    output_sh: True
# Names of meteorological files used for SOLWEIG processing
- MetFiles:
  - filename: met_20jan2022.txt
    utc_offset: 2
  - filename: met_22jan2022.txt
    utc_offset: 2
# Custom source-files that were independently created and will replace standard files pulled from CIF system.
# All four file mappings must be specified here. Specify None for file name where custom file is not available for processing.
# Standard filenames: dem.tif, dsm_ground_build.tif, tree_canopy.tif, lulc.tif
- CustomTiffFilenames:
  dem_tif_filename: None
  dsm_tif_filename: dsm_ground_build.tif
  tree_canopy_tif_filename: tree_canopy.tif
  lulc_tif_filename: lulc.tif
# Specify whether standard source-files will be retrieved from the CIF system. All four file mappings must be specified here.
# Specify "True" for CIF retrieval and "False" for no CIF retrieval in quotes.
# Retrieved filenames: cif_dem.tif, cif_dsm_ground_build.tif, cif_tree_canopy.tif, cif_lulc.tif
- RetrieveTiffFileFromCIF:
  retrieve_cif_dem_file: "False"
  retrieve_cif_dsm_file: "True"
  retrieve_cif_tree_canopy_file: "False"
  retrieve_cif_lulc_file: "False"
